### ISSUE TITLE
Storage pool `source.wipe` option behaviour is insufficient for GPT disks.

### ISSUE THREAD

**Issue by masnax** [canonical/lxd#13339]
when `source.wipe` is included with a storage pool creation request, we attempt to delete the first 4MB of data to clear the block headers: https://github.com/canonical/lxd/blob/50ee226c552216c4142eb9893d39a71b96df497e/lxd/storage/drivers/utils.go#L849-L873

However there is also data at the end of the disk that needs to be cleared out (akin to `wipefs -a`).

As such LXD might still fail to create a storage pool because the source disk has data, even if `source.wipe=true`

**Comment by tomponline** [comment]
> As such LXD might still fail to create a storage pool because the source disk has data, even if `source.wipe=true`

Thanks @masnax do you have reproducer steps that are causing an issue?

**Comment by MggMuggins** [comment]
Create a GPT partition table with `sudo fdisk /dev/sdb`:
```
Device       Start      End Sectors Size Type
/dev/sdb1     2048  6293503 6291456   3G Linux filesystem
/dev/sdb2  6293504 14682111 8388608   4G Linux filesystem
```
ZFS overwrites this just fine. 

Unrelated, but it looks like the lvm driver is trying to wipe the `lvm.vg_name` instead of the original block device.
```
$ lxc storage create lvm-pool lvm source=/dev/sdb source.wipe=true
Error: Failed to wipe headers from disk "lvm-pool": open lvm-pool: no such file or directory
```
Fixed that and it wipes over the GPT quite happily.

Btrfs is also clearly not doing the right thing:
```
$ lxc storage create btrfs-pool btrfs source=/dev/sdb source.wipe=true
Error: Failed to format sparse file: Failed to run: mkfs.btrfs -L btrfs-pool /var/lib/lxd/disks/btrfs-pool.img: exit status 1 (ERROR: '/var/lib/lxd/disks/btrfs-pool.img' is too small to make a usable filesystem
ERROR: minimum size for each btrfs device is 114294784)
```
It looks like the `blkid` introduced in #13184 is giving no output (because raw disks have no UUID), which leads to `d.config["source"]` being empty, so it tries to create the pool as a sparse file instead of on the device. I fixed that, and it failed to mount the pool after formatting `/dev/sdb`, again due to the missing UUID:
```
$ lxc storage create btrfs-pool btrfs source=/dev/sdb source.wipe=true
Error: Failed to mount "/dev/disk/by-uuid/" on "/var/lib/lxd/storage-pools/btrfs-pool" using "btrfs": block device required
```
I reran this a little while later and haven't been able to reproduce it since. The pool overwrites the GPT just fine and is created without errors.

**Comment by masnax** [comment]
I have a feeling this might be a false alarm actually. I think I'm seeing this error when the disk is obscurely stuck in use.

```
Error: Failed to run: zpool create -f -m none -O compression=on zpool /dev/sdb: exit status 1 (/dev/sdb is in use and contains a unknown filesystem.)
```

The operative part is `/dev/sdb is in use`.

It's reproducible with just the following:
```bash
mkfs.ext4 /dev/sdb
mount /dev/sdb /mnt/test

lxc storage create test dir source=/mnt/test
umount /dev/sdb

lxc storage create zpool zfs source=/dev/sdb
Error: Failed to run: zpool create -f -m none -O compression=on zpool /dev/sdb: exit status 1 (/dev/sdb is in use and contains a unknown filesystem.)
```

Thankfully in the setup above you can still see that there is a running process associated with the disk. However sometimes `zpool destroy` gets stuck and is unkillable until the VM is restarted, so the disk gets stuck in use. This can happen if the disk was previously owned by MicroCeph too, and removing the OSD failed for some reason. It becomes very hard to tell if the disk is in use (neither `ps` nor `lsof` nor `/prof/self/mountinfo` report anything useful).


Related: https://github.com/canonical/microcloud/pull/274#issuecomment-2073797401

**Comment by tomponline** [comment]
Cool will close for now, then, but if it proves to be an issue please reopen.
