### ISSUE TITLE
security.syscalls.intercept.mknod no longer seems to be working for docker [ nested ? ] use cases

### ISSUE THREAD

**Issue by jocado** [canonical/lxd#14849]
LXD: latest/edge [ ver: 6.2-bde4d03 , rev: 6.2-bde4d03 ]
OS: core24

As per per the subject:

```
# lxc config show -e test-container |grep security
  security.nesting: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
#

# lxc exec test-container /bin/bash
# docker run -it --rm --privileged busybox mknod /root/test c 1 3
mknod: /root/test: Operation not permitted
#
```

If I enable priv mode, and restart test-container:
```
# lxc config show -e test-container |grep security
  security.nesting: "true"
  security.privileged: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
#

# lxc exec test-container /bin/bash
# docker run -it --rm --privileged busybox mknod /root/test c 1 3
#
```

Outside of docker it will seems to work:
```
# lxc config show -e test-container |grep security
  security.nesting: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
#

# lxc exec test-container /bin/bash
# mknod /root/test c 1 3
# 
```

This actually came to my attention because it seems that some image layer creation can require mknod now in newer version of docker.  So a simple image pull can fail.   It seems to be image dependence, but not sure what the actual trigger is.  I don't know of any public images that container this issue I can share.

It image problem could be related to `Native Overlay Diff: true` in overlay2, but that's a complete guess on my part.  If I downgrade docker to a version that doesn't enable that with on overlay2 [ from `27.2.0` to `24.0.5` ] with the zfs or btrfs backing store, the image related error goes away.

Please let me know if you require any further info.

Thanks!

**Comment by tomponline** [comment]
@jocado does this work on 5.0/stable or 5.21/stable versions in your environment?

**Comment by tomponline** [comment]
Indeed we have similar tests here:

https://github.com/canonical/lxd-ci/blob/a5e286cd9bebf2781ae8c64e8b3ffd3c3b0a66b6/tests/interception#L35-L47

**Comment by jocado** [comment]
> [@jocado](https://github.com/jocado) does this work on 5.0/stable or 5.21/stable versions in your environment?

Seems to be the same result.

**Comment by jocado** [comment]
Just to be super clear, it works fine outside of docker still.

**Comment by jocado** [comment]
I did also find another reference to the issue [here](https://discuss.linuxcontainers.org/t/security-syscalls-intercept-mknod-still-doesnt-work/15978)

Can't be sure it's exactly the same, but I suspect it may be.

**Comment by tomponline** [comment]
Maybe one for @mihalicyn to look into when he gets a chance.

**Comment by jocado** [comment]
The main issue for us is the image loading for some images [ as mentioned above, for unknown reason some image pulls trigger a mknod, although the files referenced are certainly not device files ], but we can mitigate that by sticking on docker `24` for now.

However, we will need to upgrade at some point, and I wouldn't be surprised if another mknod related requirements presents itself eventually, even if we were able to stick on this version of docker for a while.

Anyway, thanks for taking a look 👍

**Comment by mihalicyn** [comment]
Hi @jocado,

thanks for reporting this. I can confirm that problem exists and can be reproduced in unprivileged container with mknod interception turned on like this:
```
$ unshare -m
$ mount -t overlay overlay -o lowerdir=lower,upperdir=upper,workdir=work ovl
$ mknod /root/ovl/null c 1 3
mknod: /root/ovl/null: Operation not permitted
```

It is definitely not a regression and this never worked before. Overlayfs+mknod intereception is problematic, because
overlayfs internally uses `override_creds()` and mknod interception only works in a hacky way, when we do a bindmount, instead of real `mknod`. Your case is even more problematic, as we have extra mount namespace. I've an idea how to fix this, will try and get back to you a little bit later.

>This actually came to my attention because it seems that some image layer creation can require mknod now in newer version of docker. So a simple image pull can fail. It seems to be image dependent, but not sure what the actual trigger is. I don't know of any public images that container this issue I can share.

Actually, that would be awesome to know a bit more about this. I wonder how docker version can affect on the behavior here. And also, even if problematic images are private, maybe you can somehow get me a hint about what is going on in a `Dockerfile` of these images. I mean which images they are based on? And so on... this can help us to potentially find more workarounds for you and other users too.

Kind regards,
Alex

**Comment by jocado** [comment]
Hi @mihalicyn 

Thanks very much for taking a look 👍 

> It is definitely not a regression and this never worked before

Right.  That may have been an assumption on my part, based on the linked post I referenced above.  But, I think the situation is that it used to work in nested containers [ docker inside LXC ] because until recently overlays was not used in that scenario when using either btrfs or zfs as a backing store [ docker was using the vfs driver ] .  As you point out above, overlayfs + mknod interception is the problem.

>I've an idea how to fix this, will try and get back to you a little bit later.

That sounds great - very much appreciated!

> Actually, that would be awesome to know a bit more about this

Let me see if I can dig out more info on that which is shareable.  I was also pretty curious about it when I discovered the issue.  Leave it with me, and I'll see what I can do.

Thanks!

**Comment by tomponline** [comment]
@mihalicyn any updates on this one?

**Comment by mihalicyn** [comment]
Hey @jocado,

thanks for providing this information. It is invaluable!

>failed to mknod("/usr/local/lib/python3.9/site-packages/setuptools-58.1.0.dist-info", S_IFCHR, 0): operation not permitted

This is extremely weird, because it fails to create a whiteout device. Whiteout devices are available inside the container. Please, can you try to check if it works without `security.syscalls.intercept.mknod` being set to `true`. You can just do `lxc config unset myct security.syscalls.intercept.mknod` and check if this image start to work properly. (btw, I think I've just found a bug in our interception thanks to your info...)

**Comment by jocado** [comment]
Hey.  No problem.  Glad it's proved useful 👍 

> Please, can you try to check if it works without `security.syscalls.intercept.mknod` being set to `true`

Interestingly, that does work, which seems to backup your suggestion that the it's a bug in the interception for whiteout devices.

```
# zcat /var/snap/osp-orb/current/foo.tar.gz | docker load
0238a1790324: Loading layer [==================================================>]  121.3MB/121.3MB
e6e2ab10dba6: Loading layer [==================================================>]   49.6MB/49.6MB
68866beb2ed2: Loading layer [==================================================>]  181.5MB/181.5MB
21e1c4948146: Loading layer [==================================================>]    597MB/597MB
e077e19b6682: Loading layer [==================================================>]  19.25MB/19.25MB
3aff9f9c9f44: Loading layer [==================================================>]  40.25MB/40.25MB
5e7745c5bee2: Loading layer [==================================================>]   5.12kB/5.12kB
17b02461857a: Loading layer [==================================================>]   10.5MB/10.5MB
31ee71fe1ab5: Loading layer [==================================================>]  15.05MB/15.05MB
Loaded image: foo:latest
```

I'm sure its obvious, but just to make it clear to anyone else reading, the main issue reported here doesn't work, with or without `security.syscalls.intercept.mknod` being set to `true`

**Comment by mihalicyn** [comment]
> Interestingly, that does work, which seems to backup your suggestion that the it's a bug in the interception for whiteout devices.

yep, fix is here https://github.com/canonical/lxd/pull/15634

> 
> I'm sure its obvious, but just to make it clear to anyone else reading, the main issue reported here doesn't work, with or without `security.syscalls.intercept.mknod` being set to `true`

I'm pretty sure that for 99% of docker workloads inside the container you don't need `security.syscalls.intercept.setxattr` or `security.syscalls.intercept.mknod` to be enabled. For a simple reasons:
- modern application container runtimes detect user namespace presence and has a fallback mechanism for `mknod` (see for example (https://github.com/opencontainers/runc/blob/8c72dfae65c2a03b98646c55aaa49cd5fea21ab9/libcontainer/rootfs_linux.go#L900)
- modern -/- runtimes and overlayfs support `userxattr` mount option which allows to get rid of high privilege requirements to operate xattrs in many standard cases.

Now let's get back to what you've reported initially. It was this:
```
# lxc config show -e test-container |grep security
  security.nesting: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
#

# lxc exec test-container /bin/bash
# docker run -it --rm --privileged busybox mknod /root/test c 1 3
mknod: /root/test: Operation not permitted
#
```

And yes, it doesn't work. And unfortunately, we can't really fix that on overlayfs for a reasons I described in https://github.com/canonical/lxd/issues/14849#issuecomment-2755488159
I had an idea of a potential fix, but it was wrong because it doesn't allow to make this in a reliable way. It can help to create a device node once, but then after container restart it will be a problem.

**Comment by jocado** [comment]
Hi @tomponline 

Can you confirm [this fix](https://github.com/canonical/lxd/pull/15634) made it into a release or not please ?

**Comment by tomponline** [comment]
It should be in LXD 6.4 as https://github.com/canonical/lxd/commit/1bf1b00642d7372f25d5990360634b788bcb55d7 and LXD 5.21.4 LTS as https://github.com/canonical/lxd/commit/894da46dd0767930a339c2b9b1c43032811c97af

**Comment by jocado** [comment]
ok, thanks.

Strangely, I seem to be able to re-produce the issue on lxd `6.5-ccdfb39` [ revision `36020` ].

**Comment by jocado** [comment]
Using the same test image as above:

```
root@kt-ogrp912:~/jc# zcat foo.tar.gz | docker load
0238a1790324: Loading layer [==================================================>]  121.3MB/121.3MB
e6e2ab10dba6: Loading layer [==================================================>]   49.6MB/49.6MB
68866beb2ed2: Loading layer [==================================================>]  181.5MB/181.5MB
21e1c4948146: Loading layer [==================================================>]    597MB/597MB
e077e19b6682: Loading layer [==================================================>]  19.25MB/19.25MB
3aff9f9c9f44: Loading layer [==================================================>]  40.25MB/40.25MB
5e7745c5bee2: Loading layer [==================================================>]   5.12kB/5.12kB
17b02461857a: Loading layer [==================================================>]   10.5MB/10.5MB
31ee71fe1ab5: Loading layer [==================================================>]  15.05MB/15.05MB
failed to mknod('/usr/local/lib/python3.9/site-packages/setuptools-58.1.0.dist-info', S_IFCHR, 0): operation not permitted
```

**Comment by tomponline** [comment]
Can you see if 6/stable has the same issue, as there was a fix for recent versions of runc when using `security.nesting=true` in that release.

**Comment by jocado** [comment]
I tried with the following, with the same result:

```
lxd   6.6-3c9aa6d  36883  latest/candidate  canonical✓  ignore-validation
```

**Comment by jocado** [comment]
In case it;s useful, the docker version is:
```
docker  28.4.0   3377  latest/edge  canonical✓  -
```

[ well, it is the stable docker revision, the model just tracks edge in this case ].

**Comment by jocado** [comment]
@tomponline The impact of this issue was bigger than we expected, we had too roll back a progressive release of the updated docker version across our fleet.

We are still keen too update docker though, so would be get some help on this if possible please ?

We are reverting back to docker `24.0.5`

**Comment by jocado** [comment]
It seems like a potential regression of sorts.

Please let me know if you need any more info, or any other versions I can help to test etc.

**Comment by tomponline** [comment]
My understanding from @mihalicyn is that this wasnt a regression in lxd.

Please can you advise whether this continues to work with the prior lxd or docker version, which do you think has regressed?

**Comment by tomponline** [comment]
Also are the reproducer steps above still correct?

**Comment by jocado** [comment]
Right.  I think there may be some confusion around this issue, because the original problem statement turned out not to be quite correct, in as much using `mknod` is not really the problem, and as it turned out there was no good fix for that.

The reason I actually raised this initially, was after digging into the fact that loading certain images into docker was no longer working, as it raised an error relating to `mknod`, such as:
```
failed to mknod('/usr/local/lib/python3.9/site-packages/setuptools-58.1.0.dist-info', S_IFCHR, 0): operation not permitted
```

That issue loading images turned out to be a bug in the whiteout device interception, as above.  That was supposed t be fixed with [this](https://github.com/canonical/lxd/pull/15634).  That is what it seems has somehow regressed.

The issue has now come back, when using docker `28.4.0` inside and lxc container created by LXD.  The issue is not present when loading the image in docker _not_ running inside an lxc container created by LXD.

If we revert docker to `24.0.5`, the issue is done.  I haven't done any more bisecting of LXD or Docker version than that currently.

The [above reproduction](https://github.com/canonical/lxd/issues/14849#issuecomment-2842882099), with Dockerfile and image load, is still a valid test for the issue.

There is quite a lot of good info in this issue, but I could create a new issue for this if you prefer ?

**Comment by tomponline** [comment]
No need to open a new issue.

However just so I'm clear, when you say the issue has come back/regressed, do you mean that Docker 24.0.5 works with LXD 6.6, but that the issue has re-appeared when using docker 28.4.0?

**Comment by jocado** [comment]
We are still using LXD 6.5, but essentially yes.

I did also test it with LXD 6.6, but it was the same.

When testing 6.5 this morning, I found that the issue seemed to be the same as originally report, across docker versions, which is why I'm suspecting a regression of sorts, or perhaps the [LXD fix](https://github.com/canonical/lxd/pull/15634) didn't actually solve the issue ? [ I'm not sure I validated it at the time, personally ].

With LXD 6.5, the this is the current status across a range of docker versions.

I found that these version/revisions of the docker snap have this issue:
```
27.2.0 - 2963
27.5.1 - 3064
28.4.0 - 3377
```

I found that these version/revisions of the docker snap do not have this issue:
```
24.0.5 - 2932
28.1.1 - 3221
```

**Comment by tomponline** [comment]
OK thanks, so it might be that the issue was never fixed or that some additional issue has arisen in more recent versions of docker. Thanks.

**Comment by mihalicyn** [comment]
Hi @jocado,

> Strangely, I seem to be able to re-produce the issue on lxd `6.5-ccdfb39` [ revision `36020` ].

please, can you also show `lxc config show <instance name> -e` for this container?
We need to know if `security.syscalls.intercept.mknod=true` is enabled and which image was used. Every detail is important here.

>I'm suspecting a regression of sorts, or perhaps the https://github.com/canonical/lxd/pull/15634 didn't actually solve the issue ?

That fix was only for `security.syscalls.intercept.mknod=true` case. From what I see it is merged in every supported release. Please, keep in mind that it doesn't solve the problem of mknod *inside* a docker container, but should help to run docker itself properly.

**Comment by jocado** [comment]
Hi @mihalicyn 

Sure.  I will need to prepare a test case, using a generic image, as there is some potentially sensitive info in the current `show --expanded`

I can at least confirm that `security.syscalls.intercept.mknod=true` is set.
I can also confirm that I'm not expecting to be able to use `mknod` within a docker container, just to load the images with whiteout devices.

I'll report back shortly!

**Comment by jocado** [comment]
Right!  Here is my reproduction steps, and info:

**LXD info [ for this test ]**
```
$ snap list lxd
Name  Version      Rev    Tracking       Publisher   Notes
lxd   6.6-3c9aa6d  36883  latest/stable  canonical✓  -
```

**Instance Config**
```
$ cat docker-test-instance-config.yaml
config:
  limits.kernel.nice: "-20"
  limits.kernel.rtprio: "99"
  security.idmap.isolated: "true"
  security.nesting: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
```

Docker Image
```
$ cat Dockerfile
FROM python:3.9@sha256:5c72dd8986db8c289ad1a6514319c144ed8f72c6dd702873c4358445473b6f54
RUN python -m pip --no-cache-dir install setuptools==80.0.0

$ DOCKER_BUILDKIT=1 docker build -t foo . --no-cache

$ docker save foo:latest | gzip -c > foo.tar.gz
```

**Reproduction / Test**
```
$ lxc launch ubuntu:noble docker-test < docker-test-instance-config.yaml
Launching docker-test
$ lxc exec docker-test -- snap install docker --revision 3377
2025-12-03T15:12:12Z INFO Waiting for automatic snapd restart...
docker 28.4.0 from Canonical✓ installed
$ lxc file push foo.tar.gz docker-test/root/
$ lxc exec docker-test -- bash -c "zcat foo.tar.gz | docker load" 
0238a1790324: Loading layer [==================================================>]  121.3MB/121.3MB
e6e2ab10dba6: Loading layer [==================================================>]   49.6MB/49.6MB
68866beb2ed2: Loading layer [==================================================>]  181.5MB/181.5MB
21e1c4948146: Loading layer [==================================================>]    597MB/597MB
e077e19b6682: Loading layer [==================================================>]  19.25MB/19.25MB
3aff9f9c9f44: Loading layer [==================================================>]  40.25MB/40.25MB
5e7745c5bee2: Loading layer [==================================================>]   5.12kB/5.12kB
17b02461857a: Loading layer [==================================================>]   10.5MB/10.5MB
31ee71fe1ab5: Loading layer [==================================================>]  15.05MB/15.05MB
failed to mknod('/usr/local/lib/python3.9/site-packages/setuptools-58.1.0.dist-info', S_IFCHR, 0): operation not permitted
```

For completeness, the resulting instance config:
```
$ lxc config show -e docker-test 
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 24.04 LTS amd64 (release) (20251123)
  image.label: release
  image.os: ubuntu
  image.release: noble
  image.serial: "20251123"
  image.type: squashfs
  image.version: "24.04"
  limits.kernel.nice: "-20"
  limits.kernel.rtprio: "99"
  security.idmap.isolated: "true"
  security.nesting: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
  volatile.base_image: 5aa7324e64763f9881807b6a1ad5a75f4f084fbc0ef44622153b5495dac35be0
  volatile.cloud-init.instance-id: de455a44-e6af-45bd-861d-c4b1ab8ecbe6
  volatile.eth0.host_name: veth21b07d3f
  volatile.eth0.hwaddr: 00:16:3e:b9:72:15
  volatile.idmap.base: "1065536"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1065536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1065536,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1065536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1065536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 3ca5b36b-f22c-44cb-b66a-1c0b3303c042
  volatile.uuid.generation: 3ca5b36b-f22c-44cb-b66a-1c0b3303c042
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

**Comment by jocado** [comment]
Hi @mihalicyn 👋 

I forgot to `@` you in the above message, and Just wanted to make sure you got a notification of the info I provided for you above ?

**Comment by tomponline** [comment]
Hi @jocado i mentioned this to @mihalicyn this morning.

**Comment by jocado** [comment]
Hey @tomponline 

If you could please let me know a revision I can test, and then perhaps a target revision for `6/stable`, I would be very grateful.
Thanks!

**Comment by tomponline** [comment]
Hi @jocado yeah, I'll keep an eye on the build queue and let you know once we have a 6/edge build for testing, and once confirmed you're happy with it I can cherry-pick into 6/candidate to include in the 6/stable interim release in January.

**Comment by mihalicyn** [comment]
Also, some extra context from my side https://github.com/canonical/lxd/issues/17275

**Comment by mihalicyn** [comment]
@jocado please, also consider disabling `security.syscalls.intercept.mknod` and `security.syscalls.intercept.setxattr` too. Cause this should be used and enabled only if you really need an access to `mknod` syscall. If you only need `mknod` for whiteout device, then interception is not needed. I mentioned this earlier https://github.com/canonical/lxd/issues/14849#issuecomment-2897563714

**Comment by tomponline** [comment]
@jocado this is now in 6/edge channel, revision 37183 or higher.

https://launchpad.net/~lxd-snap/lxd/+snap/lxd-latest-edge/+build/2996490

**Comment by tomponline** [comment]
@jocado this is now in `6/candidate` as revision `37188`

https://launchpad.net/~lxd-snap/lxd/+snap/lxd-latest-candidate/+build/2996647

**Comment by jocado** [comment]
> [@jocado](https://github.com/jocado) please, also consider disabling `security.syscalls.intercept.mknod` and `security.syscalls.intercept.setxattr` too. Cause this should be used and enabled only if you really need an access to `mknod` syscall. If you only need `mknod` for whiteout device, then interception is not needed. I mentioned this earlier [#14849 (comment)](https://github.com/canonical/lxd/issues/14849#issuecomment-2897563714)

I believe you are probably right.  Although it's going to be hard for us to change that in production for a little while.

One thing I want to point out here though, is that the standard instructions for running docker inside LXD from Canonical docs is to set this interception up.  I would suggest that needs to be changed, otherwise people are going to keep hitting issues related to it eventually, as highlighted over on https://github.com/canonical/lxd/issues/17275

Here is an exmaple, but there could be others:
* https://ubuntu.com/tutorials/how-to-run-docker-inside-lxd-containers#2-create-lxd-container

That could be something worth raising internally @tomponline , if you are able.

> @jocado this is now in 6/candidate as revision 37188
I will try and test that tomorrow.

Thanks again for all you help!

**Comment by tomponline** [comment]
Yes thats a good point @jocado 

I'll chat with @mionaalex about how we can update that article.

I also noticed that https://documentation.ubuntu.com/lxd/latest/howto/container_gpu_passthrough_with_docker/ and https://documentation.ubuntu.com/lxd/latest/faq/#how-can-i-run-docker-inside-a-lxd-container mentions this too.

@mihalicyn is it true to say that we dont need interception (`security.syscalls.intercept.mknod=true` and `security.syscalls.intercept.setxattr=true`) when using overlayfs with docker anymore?
